# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: <APPLICATION_NAME>
  labels:
    app: <APPLICATION_NAME>
  namespace: <NAMESPACE>
spec:
  replicas: 1
  selector:
    matchLabels:
      app: <APPLICATION_NAME>
  template:
    metadata:
      labels:
        app: <APPLICATION_NAME>
    spec:
      containers:
        - name: <APPLICATION_NAME>
          image: <REGISTRY_URL>/<IMAGE_NAME>:latest
          resources:
            requests:
              memory: 512Mi
              cpu: 250m
            limits:
              memory: 512Mi
              cpu: 250m
          ports:
            - containerPort: 80
              protocol: TCP

---
# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: <APPLICATION_NAME>
  namespace: <NAMESPACE>
spec:
  type: ClusterIP
  selector:
    app: <APPLICATION_NAME>
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
